[tool.poetry]
name = "opf"
version = "0.1.0"
description = ""
authors = ["Damian Owerko <owerko@seas.upenn.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7,<3.10"
torch = { url = "https://download.pytorch.org/whl/cu111/torch-1.8.1%2Bcu111-cp38-cp38-win_amd64.whl" }
alegnn = {path = "graph-neural-networks", develop = true}
pandapower = "^2.6.0"
numba = "^0.53.1"
julia = "^0.5.6"
pytorch-lightning = "^1.3.2"
dgl = "^0.6.1"

[tool.poetry.dev-dependencies]
comet-ml = "^3.10.0"
jupyter = "^1.0.0"
poethepoet = "^0.10.0"
black = "^21.5b2"

[tool.poe.tasks]
force-cuda11 = "python -m pip install torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html"

[tool.poetry.scripts]
generate = 'opf.generate:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
