[tool.poetry]
name = "opf"
version = "0.1.0"
description = ""
authors = ["Damian Owerko <owerko@seas.upenn.edu>"]
license = "MIT"

[[tool.poetry.source]]
name = "pytorch"
url = "https://eternalphane.github.io/pytorch-pypi/"

[tool.poetry.dependencies]
python = "^3.8,<3.10"
alegnn = {path = "graph-neural-networks", develop = true}
pandapower = {git = "https://github.com/e2nIEE/pandapower.git", branch="develop"}
julia = "^0.5.7"
pytorch-lightning = "^1.3.2"
numpy = "^1.21.4"
numba = "^0.53.1"
torch = "1.10.1+cu113"
neptune-client = "^0.14.0"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
black = "^21.5b2"
wandb = "^0.12.4"
pytest = "^6.2.4"
seaborn = "^0.11.1"
pandoc = "^1.1.0"
pandas = "^1.3.2"
filelock = "<3.2.0"
guildai = "^0.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
