[tool.poetry]
name = "opf"
version = "0.1.0"
description = ""
authors = ["Damian Owerko <owerko@seas.upenn.edu>"]
license = "MIT"

[[tool.poetry.source]]
name = "pytorch"
url = "https://eternalphane.github.io/pytorch-pypi/"

[tool.poetry.dependencies]
python = "^3.8,<3.10"
alegnn = {path = "graph-neural-networks", develop = true}
pandapower = "^2.10.1"
pandas = "^1.5.2"
julia = "^0.6.0"
pytorch-lightning = "^1.8.3.post1"
numpy = "^1.23.5"
torch = "1.10.1+cu113"
jupyter = "^1.0.0"
black = "^22.10.0"
wandb = "^0.13.6"
pytest = "^7.2.0"
seaborn = "^0.12.1"
pandoc = "^2.3"
guildai = "^0.8.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
