[tool.poetry]
name = "opf"
version = "0.1.0"
description = ""
authors = ["Damian Owerko <owerko@seas.upenn.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.10"
alegnn = {path = "graph-neural-networks", develop = true}
pandapower = "^2.6.0"
julia = "^0.5.6"
pytorch-lightning = "^1.3.2"
torch = "~1.9.0"
numpy = "~1.19.5"
numba = "^0.53.1"
guildai = "^0.7.3"

[tool.poetry.dev-dependencies]
comet-ml = "^3.10.0"
jupyter = "^1.0.0"
black = "^21.5b2"
wandb = "^0.10.31"
poethepoet = "^0.10.0"
pytest = "^6.2.4"
seaborn = "^0.11.1"
pandoc = "^1.1.0"
pandas = "^1.3.2"

[tool.poetry.scripts]
generate = 'opf.generate:main'

[tool.poe.tasks]
cuda11 = "python -m pip install torch==1.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
