#!/bin/bash
set -e
REPOSITORY="docker.io"
IMAGE_NAME="opf"
DOCKER_USERNAME="damowerko"
export DOCKER_BUILDKIT=1
docker pull $REPOSITORY/$DOCKER_USERNAME/$IMAGE_NAME:latest || true
docker build . -t $REPOSITORY/$DOCKER_USERNAME/$IMAGE_NAME --build-arg BUILDKIT_INLINE_CACHE=1  --build-arg REPOSITORY=$REPOSITORY
docker push $REPOSITORY/$DOCKER_USERNAME/$IMAGE_NAME