apiVersion: v1
kind: Pod
metadata:
  name: optuna
  namespace: owerko
  labels:
    app: optuna
spec:
  containers:
  - name: optuna-db
    image: postgres:latest
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: "optuna"
    - name: POSTGRES_PASSWORD
      value: "optuna"
  # - name: optuna-dashboard
  #   image: ghcr.io/optuna/optuna-dashboard
  #   args: ["postgresql+psycopg2://optuna:optuna@optuna.owerko.svc.cluster.local:5432/optuna", "--host", "0.0.0.0"]
  #   ports:
  #   - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: optuna
  namespace: owerko
  labels:
    app: optuna
spec:
  type: NodePort
  selector:
    app: optuna
  ports:
  - port: 5432
    name: db
    protocol: TCP
    nodePort: 31234
  # - port: 8080
  #   name: dashboard
  #   protocol: TCP
---
# ingress for optuna-dashboard
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: optuna-dashboard
#   namespace: owerko
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#   - host: cluster.local
#     http:
#       paths:
#       - path: /owerko/optuna(/|$)(.*)
#         pathType: Prefix
#         backend:
#           service:
#             name: optuna
#             port:
#               number: 8080