#!/bin/bash


gpu_count=$(nvidia-smi --query-gpu=name --format=csv,noheader | wc -l)

gpu=-1
cpu=-1

while [ "$1" != "" ]; do
    case $1 in
        --gpu )
            shift
            gpu=$(($1-1))
        ;;
        --cpu )
            shift
            cpu=$(($1-1))
        ;;
        * )
            echo "Invalid argument $1 $2"
            exit 1
    esac
    shift
done


for i in $(seq 0 $gpu)
do
    guild run --gpus $(($i%$gpu_count)) --background -y queue 
done

for i in $(seq 0 $cpu) 
do
    guild run --no-gpus --background -y queue
done