F: 32
K: 8
L: 2
activation: leaky_relu
adj_threshold: 0.01
batch_size: 256
case_name: case30
constraint_features: 0
cost_weight: 0.01
data_dir: ./data
enforce_constraints: 0
eps: 0.0001
fast_dev_run: false
gpus: 1
gradient_clip_val: 0.0
hotstart: null
log: 1
log_dir: ./logs
lr: 0.0003
max_epochs: 2000
patience: 1000
readout: local
root_dir: ./
s: 10
t: 500
wandb: 1
